services:

  apache:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: practicas_apache
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: practicas_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practicas
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: practicas_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql_data: